
# devops-1/your_own_shopping_store/Frontend/Dockerfile

FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
ENV VITE_API_URL=http://localhost:5000
ENV VITE_BASE_URL=http://localhost:5000
ENV BASE_URL=http://localhost:5000
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
